//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAllInfomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int idCash { get; set; }
        public int idStock { get; set; }
        public int idSession { get; set; }
        public int idCashField { get; set; }
        public string valueCash { get; set; }
        public int idYear { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual CashFields CashFields { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Year Year { get; set; }
    }
}
