//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAllInfomation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
            this.Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stock> StockSet { get; set; }
        public virtual DbSet<AssetsFields> AssetsFieldsSet { get; set; }
        public virtual DbSet<Assets> AssetsSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<AssetsFieldsGroup> AssetsFieldsGroupSet { get; set; }
        public virtual DbSet<Performance> PerformanceSet { get; set; }
        public virtual DbSet<PerformanceFields> PerformanceFieldsSet { get; set; }
        public virtual DbSet<Month> MonthSet { get; set; }
        public virtual DbSet<SaleMonth> SaleMonthSet { get; set; }
        public virtual DbSet<SaleMonthFields> SaleMonthFieldsSet { get; set; }
        public virtual DbSet<Cash> CashSet { get; set; }
        public virtual DbSet<CashFields> CashFieldsSet { get; set; }
        public virtual DbSet<Income> IncomeSet { get; set; }
        public virtual DbSet<IncomeFields> IncomeFieldsSet { get; set; }
        public virtual DbSet<IncomeFieldGroup> IncomeFieldGroupSet { get; set; }
        public virtual DbSet<Year> YearSet { get; set; }
        public virtual DbSet<Dividend> DividendSet { get; set; }
        public virtual DbSet<DivendendFields> DivendendFieldsSet { get; set; }
    }
}
